from django.db import models

# Create your models here.

class Segmentation(models.Model):
    caseID = models.IntegerField()
    segID = models.IntegerField()
    seg = models.CharField(max_length=255)
    is_selected = models.BooleanField()

    class Meta:
        unique_together = ("caseID","segID")

class ClusterImg(models.Model):
    caseID = models.IntegerField(primary_key=True)
    imgPath = models.CharField(max_length=255)

class Category(models.Model):
    Internal_ID = models.IntegerField()
    Internal_case_code = models.IntegerField()
    Orginal_Class = models.CharField(max_length=255)
    Case_No = models.IntegerField(primary_key=True)
    Reference_No =models.IntegerField()
    Scan_Date = models.CharField(max_length=255)
    Remarks = models.CharField(max_length=255)
    HCC_raw_HKU = models.IntegerField()
    HCC_HKU_DATABASE = models.CharField(max_length=255)
    Cirrhosis_FIB_4_score = models.FloatField()
    Cirrhosis_HKU_DATABASE = models.CharField(max_length=255)
    Cirrhosis_Hx_from_radi = models.CharField(max_length=255)
    Cirrhosis = models.CharField(max_length=255)
    Hepatitis_Category = models.IntegerField()
    Hepatitis = models.CharField(max_length=255)

class Detail(models.Model):
    Internal_case_code = models.IntegerField(primary_key=True)
    Internal_ID = models.IntegerField()
    Code = models.CharField(max_length=255)
    problem = models.CharField(max_length=255)
    Accession_no = models.IntegerField()
    DOB = models.CharField(max_length=255)
    Age = models.IntegerField()
    Gender = models.IntegerField()
    Scan_date = models.CharField(max_length=255)
    HBsAg = models.IntegerField()
    HBeAg = models.IntegerField()
    Albumin = models.IntegerField()
    Bilirubin = models.IntegerField()
    ALP = models.IntegerField()
    ALT = models.IntegerField()
    AST = models.IntegerField()
    GGT = models.IntegerField()
    HGB = models.FloatField()
    WBC = models.FloatField()
    Platelet = models.IntegerField()
    INR = models.FloatField()
    AFP = models.IntegerField()
    HBV_D_1 = models.CharField(max_length=255)
    Anti_HCV = models.CharField(max_length=255)
    HCV_D_1 = models.CharField(max_length=255)
    Liver_disease = models.CharField(max_length=255)
    Fibrosis_4 = models.FloatField()
    Dx1 = models.CharField(max_length=255)
    Size1 = models.CharField(max_length=255)
    location1 = models.CharField(max_length=255)
    Validated_Dx1 = models.CharField(max_length=255)
    Dx2 = models.CharField(max_length=255)
    Size2 = models.CharField(max_length=255)
    location2 = models.CharField(max_length=255)
    Validated_Dx2 = models.CharField(max_length=255)
    Dx3 = models.CharField(max_length=255)
    Size3 = models.CharField(max_length=255)
    location3 = models.CharField(max_length=255)
    Validated_Dx3 = models.CharField(max_length=255)
    Dx4 = models.CharField(max_length=255)
    Size4 = models.CharField(max_length=255)
    location4 = models.CharField(max_length=255)
    Validated_Dx4 = models.CharField(max_length=255)
    Clinical_Dx4 = models.CharField(max_length=255)
    IntraOp_Validation_Dx4 = models.CharField(max_length=255)
    Radiological_Dx4 = models.CharField(max_length=255)
    Radi_Validated_Date_Dx4 = models.CharField(max_length=255)
    Validated_modality_Dx4 = models.CharField(max_length=255)
    Pathological_Dx4 = models.CharField(max_length=255)
    Differentiation_Dx4 = models.CharField(max_length=255)
    Dx5 = models.CharField(max_length=255)
    Size5 = models.CharField(max_length=255)
    location5 = models.CharField(max_length=255)
    Validated_Dx5 = models.CharField(max_length=255)
    Clinical_Dx5 = models.CharField(max_length=255)
    IntraOp_Validation_Dx5 = models.CharField(max_length=255)
    Radiological_Dx5 = models.CharField(max_length=255)
    Radi_Validated_Date_Dx5 = models.CharField(max_length=255)
    Validated_modality_Dx5 = models.CharField(max_length=255)
    Pathological_Dx5 = models.CharField(max_length=255)
    Differentiation_Dx5 = models.CharField(max_length=255)
    AI_algorithms = models.CharField(max_length=255)
    Dx6 = models.CharField(max_length=255)
    Size6 = models.CharField(max_length=255)
    location6 = models.CharField(max_length=255)
    Validated_Dx6 = models.CharField(max_length=255)
    Clinical_Dx6 = models.CharField(max_length=255)
    IntraOp_Validation_Dx6 = models.CharField(max_length=255)
    Radiological_Dx6 = models.CharField(max_length=255)
    Radi_Validated_Date_Dx6 = models.CharField(max_length=255)
    Validated_modality_Dx6 = models.CharField(max_length=255)
    Pathological_Dx6 = models.CharField(max_length=255)
    Differentiation_Dx6 = models.CharField(max_length=255)
    Dx7 = models.CharField(max_length=255)
    Size7 = models.CharField(max_length=255)
    location7 = models.CharField(max_length=255)
    Validated_Dx7 = models.CharField(max_length=255)
    Clinical_Dx7 = models.CharField(max_length=255)
    IntraOp_Validation_Dx7 = models.CharField(max_length=255)
    Radiological_Dx7 = models.CharField(max_length=255)
    Radi_Validated_Date_Dx7 = models.CharField(max_length=255)
    Radiological_Rpt_CT = models.TextField()
