# Generated by Django 3.2.13 on 2022-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.IntegerField()),
                ('segID', models.IntegerField()),
                ('seg', models.CharField(max_length=255)),
                ('is_selected', models.BooleanField()),
            ],
            options={
                'unique_together': {('caseID', 'segID')},
            },
        ),
    ]
